### ISSUE TITLE
tf-2.4.0: TypeError: Variable is unhashable. Instead, use tensor.ref() as the key.

### ISSUE THREAD

**Issue by Yonma** [ben-davidson-6/Gated-SCNN#13]
I met this error when training use 'cityscapes_model.py'

**tensorflow version: 2.4.0**

I thought it was caused by the version compatibility, and most answers I found said so. They either deactivated the eager mode or changed tf version to 1.x, but none of them act well on my computer.

 I've tried two ways to solve, but both failed:

1. As the document of tensorflow says, add .ref() after tensor/variable (string can't):
https://www.tensorflow.org/api_docs/python/tf/Variable (search: unhashabel)
tf.Tensor part said simliar thing: use tensor/variable.ref() as keys of dict and use tensor/variable.ref() to fetch values.

I used a shared tensor/variable (both tried): sa.ref(),sb.ref(),sc,sd to replace 's1','s2'...in the dict of outputs.
(tensor/variable defined in  model_fefinition.py of, then imported in layers.py, both under the folder 'model')

But the error still exists.

2. I thought the keras..Mode's multi-outputs part might be helpful.

so I used a list follows the way in keras official documents:
https://www.tensorflow.org/guide/keras/functional (search: outputs=)
and used list[index] to fetch these features.

While the same error appear again.

I can't come up with another way to figure this out, hope someone could help me, that'll help me a lot.

**Comment by ben-davidson-6** [comment]
can you try with tensorflow==2.3 as a first step

**Comment by Yonma** [comment]
> can you try with tensorflow==2.3 as a first step

tks for replying.

I've tried just now, I saw my gpu resources being used when using 2.3 which means it runs at least.

While when I changed to tf-2.4 (used pip install to change), the error raised again,
just after the screen showed: epoch 0 training

so...seems that its a problem caused by tf updates.

**Comment by Yonma** [comment]
I've tried create multi-outputs model in my own codebase, everything goes fine in your codes' model-build style. I'm going to check the traning part later if I have some time.

**Comment by Yonma** [comment]
I moved codes to my own repo, it runs fine. I learned a lot recently, thanks for sharing.
