### ISSUE TITLE
Training time, dualtask loss?

### ISSUE THREAD

**Issue by AZ-Visuals** [ben-davidson-6/Gated-SCNN#2]
Hi. I would like to know how much time it took for you to train the model without final atrous spatial pyramid pooling?

Also, as far as I can see, you are not using dualtask loss, right?

**Comment by ben-davidson-6** [comment]
I always trained with atrous spatial ppyramid pooling, the problem was I did not replace down sampling layers in the backbone network with atrous convolutions. Under that network it took around 2 days to train on a single GPU.

I do use a dual task loss as well.

**Comment by aoe24** [comment]
Hi, I am a graduate student, can you use your code for experiments? I will attach the link in my paper and write your name in the acknowledgments.THANK YOU VERY MUCH!

**Comment by ben-davidson-6** [comment]
Sure :)
