### ISSUE TITLE
Generating edge masks

### ISSUE THREAD

**Issue by ben-davidson-6** [ben-davidson-6/Gated-SCNN#5]
(creating an issue relating to an email I got from someone)

I have a question on your code and was wondering if it could work on my dataset with just the images and mask segmentation in jpg files, and how to get the edge label from the masks if its required.

**Comment by ben-davidson-6** [comment]
Np, I should probably mention it somewhere on the repo actually. If you have your segmentations you can generate edge masks with the code. The relevant function is `dataset.utils.flat_label_to_edge_label`. You will need to use this function to generate all the edge images and save them before training.

**Comment by nifix586** [comment]
Thank you for the response, I'm trying to use mobilenet as backbone, any advice?

**Comment by benDavidson6** [comment]
You would just need to replace the Xception layer. If you do `tf.keras.application.Mobilenet().summary` then you can see the name of the final layer which does some downsampling, and replace it with atrous convolution so that it does not downsample them (I do this in  `gscnn.model.atrous_xception.py` for Xception)

**Comment by nifix586** [comment]
Hi Ben,

so i tried running the code using a custom dataset (coco dataset) and i kept getting this error : 
InvalidArgumentError: Invalid reduction dimension (0 for input with 0 dimension(s) [Op:Any]
which is coming from this loss function in loss.py inside the training folder
`def loss(gt_label, logits, shape_head, edge_label, loss_weights):

    # in cityscapes we ignore some classes, which means that there will
    # be pixels without any class
    keep_mask = tf.reduce_any(gt_label == 1., axis=0)` 

I also checked if there was a gt_label and it printed the gt_label but still threw this error
Please can you help?

**Comment by nifix586** [comment]
The axis is originally set to "axis = -1" in your code, but when i use none as axis it works, please is it advisable to set the axis as none and reduce all dimensions in the truth_label as opposed to -1 axis

**Comment by benDavidson6** [comment]
your gt_label should be of shape [batch, height, width, num_classes], so that when you do `keep_mask = tf.reduce_any(gt_label == 1., axis=-1)` it is just checking that one of the classes is 'on'. It looks like you are trying to feed in a `gt_label` which exists but is the wrong shape.

**Comment by nifix586** [comment]
Thanks for your response and Yes the gt_label is of [4, 700,700,2] as shape, i am using 2 classes for foreground(person) and background

**Comment by ben-davidson-6** [comment]
hmm thats odd, if it were of shape `[4, 700,700,2]` it would work. I think somehow, an image must get fed to it which has no shape, can you share your dataset with me

**Comment by ben-davidson-6** [comment]
I am going to close this issue and start another one with the error you are getting
