### ISSUE TITLE
InvalidArgumentError: Invalid reduction dimension (0 for input with 0 dimension(s) [Op:Any]

### ISSUE THREAD

**Issue by ben-davidson-6** [ben-davidson-6/Gated-SCNN#6]
Hi Ben,

so i tried running the code using a custom dataset (coco dataset) and i kept getting this error : 
InvalidArgumentError: Invalid reduction dimension (0 for input with 0 dimension(s) [Op:Any]
which is coming from this loss function in loss.py inside the training folder
`def loss(gt_label, logits, shape_head, edge_label, loss_weights):

    # in cityscapes we ignore some classes, which means that there will
    # be pixels without any class
    keep_mask = tf.reduce_any(gt_label == 1., axis=0)` 

I also checked if there was a gt_label and it printed the gt_label but still threw this error
Please can you help?

_Originally posted by @nifix586 in https://github.com/ben-davidson-6/Gated-SCNN/issues/5#issuecomment-632117892_

**Comment by ben-davidson-6** [comment]
your gt_label should be of shape [batch, height, width, num_classes], so that when you do keep_mask = tf.reduce_any(gt_label == 1., axis=-1) it is just checking that one of the classes is 'on'. It looks like you are trying to feed in a gt_label which exists but is the wrong shape.

**Comment by nifix586** [comment]
`class Dataset:
    """
    All custom datasets should inherit from this class. To do so you need to provide two methods
        self.get_paths(train) -> image_paths, label_paths, edge_paths
        self.flat_to_one_hot(labels, edges) -> converts flat segmentations (h, w) to one_hot (h, w, c)
    """

    def __init__(
            self,
            tfrecord_dir,
            batch_size,
            network_input_h,
            network_input_w,
            max_crop_downsample,
            colour_aug_factor,
            buffer_size,
            num_classes):
        """
        :param val_batch_size:
        :param batch_size:
        :param max_crop_downsample how far we will scale cropping window:
        :param colour_aug_factor:
        :param debug setting to true will give you a dataset with 1 element for both train and val:
        """
        self.tfrecord_dir = tfrecord_dir
        self.batch_size = batch_size
        self.network_input_h = network_input_h
        self.network_input_w =  network_input_w
        self.max_crop_downsample = max_crop_downsample
        self.colour_aug_factor = colour_aug_factor
        self.buffer_size = buffer_size
        self.num_classes = num_classes
        
    def _parse_tfrecord(self,tfrecord):
        features = {
        'image_raw': tf.io.FixedLenFeature([], tf.string),
        'mask_raw': tf.io.FixedLenFeature([], tf.string),
        'edge_raw': tf.io.FixedLenFeature([], tf.string),
        }
        x = tf.io.parse_single_example(tfrecord, features)
        image = tf.image.decode_jpeg(x['image_raw'], channels=3)
        mask = tf.image.decode_jpeg(x['mask_raw'], channels=3)
        edge = tf.image.decode_jpeg(x['edge_raw'], channels=3)
        return (image, mask, edge)

    def crop_size(self, all_input_shape):
        """
        :param all_input_shape [h, w, 3+c+2] the shape of every input with the channels concated:
        :return the size of the random crop:
        """
        # we can only crop as much as the smallest dimension
        max_size = tf.reduce_min(all_input_shape[:2])
        max_crop_size = tf.stack([max_size, max_size])

        # get random amount to scale by
        reduction = tf.random.uniform(
            shape=[],
            minval=self.max_crop_downsample,
            maxval=1.)
        crop_size = tf.cast(max_crop_size, tf.float32)*reduction
        crop_size = tf.cast(crop_size, tf.int32)

        crop = tf.concat([crop_size, all_input_shape[-1:]], axis=0)
        return crop

    def crop_images(self, image, label, edge_label):
        """
        :param image tensor:
        :param label tensor:
        :param edge_label tensor:
        :return cropped image, cropped label, cropped edge:
        randomly crop the data, with a random sized crop
        """

        # concat all inputs so we can crop them in the same random manner
        all_input_tensor = tf.concat([image, label, edge_label], axis=-1)
        tensor_shape = tf.shape(all_input_tensor)

        # random crop size
        crop_size = self.crop_size(tensor_shape)

        # crop the images
        cropped = tf.image.random_crop(all_input_tensor, crop_size)
        return cropped[..., :3], cropped[..., 3:4], cropped[..., 4:]
    def resize_images(self, image, label, edge_label):
        """
        :param image tensor:
        :param label tensor:
        :param edge_label tensor:
        :return resized data:
        resize data, for training all inputs are shaped (self.network_input_h, self.network_input_w)
        """
        image = tf.image.resize(image, (self.network_input_h, self.network_input_w))
        label = tf.image.resize(label, (self.network_input_h, self.network_input_w), method='nearest')
        edge_label = tf.image.resize(edge_label, (self.network_input_h, self.network_input_w), method='nearest')
        return image, label, edge_label

    def colour_jitter(self, image,):
        image = tf.image.random_brightness(image, self.colour_aug_factor)
        image = tf.image.random_saturation(
            image, 1. - self.colour_aug_factor, 1 + self.colour_aug_factor)
        image = tf.image.random_contrast(
            image, 1. - self.colour_aug_factor, 1 + self.colour_aug_factor)
        image = tf.image.random_hue(image, self.colour_aug_factor)
        return image

    def random_flip(image, label, edge):
        """random left right flips"""
        all_tensors = tf.concat([image, label, edge], axis=-1)
        all_tensors = tf.image.random_flip_left_right(all_tensors[None])[0]
        return all_tensors[..., :3], all_tensors[..., 3:4], all_tensors[..., 4:]

    def flat_to_one_hot(self,labels, edges):
        labels = tf.one_hot(labels[..., 0], self.num_classes)
        edges = tf.one_hot(edges[..., 0], 2)
        return labels, edges

    def process_training_batch(self,images, labels, edges):
        """batch convert to one hot and apply colour jitter"""
        labels, edges = self.flat_to_one_hot(labels, edges)
        images = tf.cond(
            tf.greater(tf.random.uniform([]), 0.5),
            lambda: self.colour_jitter(images),
            lambda: images)
        return images, labels, edges 

    def build_training_dataset(self,shuffle=True):
        dataset = tf.data.TFRecordDataset(self.tfrecord_dir)
        dataset = dataset.repeat()
        if shuffle:
            dataset = dataset.shuffle(buffer_size=self.buffer_size)
        dataset = dataset.map(self._parse_tfrecord)
        dataset = dataset.map(Dataset.random_flip, num_parallel_calls=tf.data.experimental.AUTOTUNE)
        dataset = dataset.map(self.crop_images, num_parallel_calls=tf.data.experimental.AUTOTUNE)
        dataset = dataset.map(self.resize_images, num_parallel_calls=tf.data.experimental.AUTOTUNE)
        dataset = dataset.batch(self.batch_size, drop_remainder=True)
        dataset = dataset.map(self.process_training_batch, num_parallel_calls=tf.data.experimental.AUTOTUNE)
        dataset = dataset.prefetch(tf.data.experimental.AUTOTUNE)
        
        #if self.debug:
        dataset = dataset.take(1)
        return dataset
`

**Comment by nifix586** [comment]
I used tfrecord for my dataset

**Comment by ben-davidson-6** [comment]
if you iterate over your dataset as below do you get the same output as me.
```python
    for x, y, z in dataset.build_training_dataset():
        print(x.shape, x.dtype) # (4, 700, 700, 3)   <dtype: 'float32'>
        print(y.shape, y.dtype) # (4, 700, 700, 19) <dtype: 'float32'> this will have a different number of channels unless your task also has 19 classes
        print(z.shape, z.dtype) # (4, 700, 700, 2)   <dtype: 'float32'>
```

Ideally you should be subclassing the `Dataset` class and just implementing a method which returns the list of paths where image, labels, and edges are. Alternatively you can do what you are doing and define your own dataset the dataset just needs to output three things, of the same format as in the loop above. 

If you look in the readme this is explained better now, and if you use the most up  to date version of the code you can just follow the readme.

**Comment by nifix586** [comment]
Yeah the dataset is outputing that shape for the 3 images 
(4, 700, 700, 3) <dtype: 'float32'>
(4, 700, 700, 2) <dtype: 'float32'>
(4, 700, 700, 2) <dtype: 'float32'>

**Comment by ben-davidson-6** [comment]
can you copy paste the full error you get, this doesnt make any sense :D

**Comment by nifix586** [comment]
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-6-74adcd61945f> in <module>()
     22         print(z.shape, z.dtype)
     23         print(tf.rank(y, name = None))
---> 24         keep_mask = tf.reduce_any(y == 1., axis=-1)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    178     """Call target, and fall back on dispatchers if there is a TypeError."""
    179     try:
--> 180       return target(*args, **kwargs)
    181     except (TypeError, ValueError):
    182       # Note: convert_to_eager_tensor currently raises a ValueError, not a

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py in reduce_any(input_tensor, axis, keepdims, name)
   2297       gen_math_ops._any(
   2298           input_tensor, _ReductionDims(input_tensor, axis), keepdims,
-> 2299           name=name))
   2300 
   2301 

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py in _any(input, axis, keep_dims, name)
    776       else:
    777         message = e.message
--> 778       _six.raise_from(_core._status_to_exception(e.code, message), None)
    779   # Add nodes to the TensorFlow graph.
    780   if keep_dims is None:

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: Invalid reduction dimension (-1 for input with 0 dimension(s) [Op:Any]

**Comment by ben-davidson-6** [comment]
What version of tf are you using?

**Comment by nifix586** [comment]
tensorflow==2.0.0-beta1

**Comment by ben-davidson-6** [comment]
OK you will need to update it to 2.2.0 for the rest of the training to work. Can you try running this:
```python
y = tf.constant([[0., 1., 1.]])
    keep_mask = tf.reduce_any(
        y == 1.
        axis=-1)
```

**Comment by nifix586** [comment]
Ok, I have switched to 2.2.0 but still throws the error after running this code 
`y = tf.constant([[0., 1., 1.]])
keep_mask = tf.reduce_any(
        y == 1.
        axis=-1)`

**Comment by nifix586** [comment]
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-12-f319c4d62441> in <module>()
      2 keep_mask = tf.reduce_any(
      3         y == 1.,
----> 4         axis=-1)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    178     """Call target, and fall back on dispatchers if there is a TypeError."""
    179     try:
--> 180       return target(*args, **kwargs)
    181     except (TypeError, ValueError):
    182       # Note: convert_to_eager_tensor currently raises a ValueError, not a

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py in reduce_any(input_tensor, axis, keepdims, name)
   2297   are retained with length 1.
   2298 
-> 2299   If `axis` is None, all dimensions are reduced, and a
   2300   tensor with a single element is returned.
   2301 

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py in _any(input, axis, keep_dims, name)
    776         "ApproximateEqual", _inputs_flat, _attrs, _result)
    777   _result, = _result
--> 778   return _result
    779 
    780 ApproximateEqual = tf_export("raw_ops.ApproximateEqual")(_ops.to_raw_op(approximate_equal))

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: Invalid reduction dimension (-1 for input with 0 dimension(s) [Op:Any]

**Comment by nifix586** [comment]
So i should reinstall it?

**Comment by nifix586** [comment]
Thank you so much
